import type { Metadata } from "next";
import Navigation from "@/app/components/navigation";
import "./globals.css";
import Footer from "@/app/components/footer";
import StyledComponentsRegistry from "@/lib/registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Navigation />
          {children}
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
